[build]
  publish = "build"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  environment = { NODE_VERSION = "16.13.2" }

[build.environment]
    NPM_FLAGS = "--version" # prevent Netlify npm install
